version: '3.8'

services:
  mongo:
    container_name: mongodb
    image: mongo:4.2.20-rc0
    ports: 
      - "27017:27017"
      - "28017:28017"
    env_file:
      - ../.env

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    env_file:
      - ../.env